### ISSUE TITLE
Socket.IO Client 1.3.2 XHR Polling Issue

### ISSUE THREAD

**Issue by JonmarkWeber** [mrniko/netty-socketio#200]
About 4 days ago a new version of the Socket.IO client was released.  With this release it seems that the XHR Polling connection process has changed.  In 1.2.1 you were getting binary data, and identifying the that the packet was not a String packet, and then skipping the binary header data and processing the packet like normal.  In 1.3.2 you first receive this packet from the client:

35:40/namespace

Which obviously is not binary data, so then you take the first character as the packet type (pong) and your done...  Then the client sends this packet:

:40/namespace

And you translate the first character into a packet type (integer 10) which does not correspond to a packet type and it fails.  The 4 after the : is the actual packet type, though I am not sure why this format has changed between 1.2.1 and 1.3.2.  We have reverted back to using the 1.2.1 client until the Netty Socket.IO is updated to work with the 1.3.2 Socket.IO Client.

I only understand enough to get this data to you, and it seems like a issue that needs solving on the Netty Socket.IO side, though you would know better if its actually a issue with the Socket.IO Client.

**Comment by mrniko** [comment]
is this an only one bug with 1.3.x client? Have you encountered with any other problems with new client?

**Comment by JonmarkWeber** [comment]
This issue was preventing me from getting any further into the code.  Since XHR connections were prevented the Socket.IO connection was flagged as disconnected, and would not send any packets to the server.  I did however see that the pings which were being sent by the client over WebSockets were being received on Netty Socket.IO and responded to.

So I suspect once this issue is resolved, everything else should "just work", but that is just a guess.

**Comment by evgeny-pasynkov** [comment]
exception after upgrading client to socket.io 1.3.2:

[2015-01-24 13:21:53,597] ERROR etty worker group-17 cketio.handler.InPacketHandler - Error during data processing. Client sessionId: ca790814-cfb6-48f1-a346-dbe2109795c3, data: 3:42[xxxxxxxxx] 
java.lang.IllegalStateException
	at com.corundumstudio.socketio.protocol.PacketType.valueOfInner(PacketType.java:57)
	at com.corundumstudio.socketio.protocol.PacketDecoder.readInnerType(PacketDecoder.java:90)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decode(PacketDecoder.java:144)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:114)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.jetbrains.upsource.netty.handlers.SimpleChannelInboundHandlerEx.channelRead(SimpleChannelInboundHandlerEx.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at com.corundumstudio.socketio.transport.PollingTransport.onPost(PollingTransport.java:161)
	at com.corundumstudio.socketio.transport.PollingTransport.handleMessage(PollingTransport.java:120)
	at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:97)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.corundumstudio.socketio.handler.AuthorizeHandler.channelRead(AuthorizeHandler.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.jetbrains.upsource.netty.handlers.SimpleChannelInboundHandlerEx.channelRead(SimpleChannelInboundHandlerEx.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.jetbrains.upsource.netty.handlers.SimpleChannelInboundHandlerEx.channelRead(SimpleChannelInboundHandlerEx.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

**Comment by evgeny-pasynkov** [comment]
Moreover, pseudo-official java client was bumped to support protocol change:
https://github.com/nkzawa/socket.io-client.java

**Comment by mrniko** [comment]
@evgeny-pasynkov a lot of changes there!

**Comment by evgeny-pasynkov** [comment]
I think they do know what they'r doing, since 'nkzawa' is one of the original socket.io developers

**Comment by mrniko** [comment]
fixed. please check. compatiblity with previous versions socket.io client has been retained

**Comment by evgeny-pasynkov** [comment]
Nope, not fixed. Fresh exception:

java.lang.IndexOutOfBoundsException: UnpooledUnsafeDirectByteBuf(ridx: 23, widx: 600, cap: 600).slice(24, 193084926)
	at io.netty.buffer.SlicedByteBuf.<init>(SlicedByteBuf.java:42)
	at io.netty.buffer.AbstractByteBuf.slice(AbstractByteBuf.java:938)
	at com.corundumstudio.socketio.protocol.PacketDecoder.decodePackets(PacketDecoder.java:135)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:65)
	at com.corundumstudio.socketio.handler.InPacketHandler.channelRead0(InPacketHandler.java:36)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.jetbrains.upsource.netty.handlers.SimpleChannelInboundHandlerEx.channelRead(SimpleChannelInboundHandlerEx.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at com.corundumstudio.socketio.transport.WebSocketTransport.channelRead(WebSocketTransport.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.corundumstudio.socketio.transport.PollingTransport.channelRead(PollingTransport.java:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.corundumstudio.socketio.handler.AuthorizeHandler.channelRead(AuthorizeHandler.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.jetbrains.upsource.netty.handlers.SimpleChannelInboundHandlerEx.channelRead(SimpleChannelInboundHandlerEx.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at com.jetbrains.upsource.netty.handlers.SimpleChannelInboundHandlerEx.channelRead(SimpleChannelInboundHandlerEx.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mrniko** [comment]
i need a packet data which case this bug

**Comment by mrniko** [comment]
because i can't reproduce

**Comment by evgeny-pasynkov** [comment]
Please check the debugger screenshot. We've got '2probe' in input, and you're trying to read binary long 

![image](https://cloud.githubusercontent.com/assets/7429642/5961536/bc60efa0-a7dd-11e4-9c6b-b8690e190dd2.png)

**Comment by mrniko** [comment]
now should works well

**Comment by evgeny-pasynkov** [comment]
From the first look, it works! Great job, thank you.
Will run full test pack tomorrow and report here

**Comment by evgeny-pasynkov** [comment]
BTW, you can add JetBrains Upsource (code review system) as a solution using netty-socketio.
http://www.jetbrains.com/upsource

**Comment by evgeny-pasynkov** [comment]
All tests passed. Thanks once more!

**Comment by JonmarkWeber** [comment]
Is there a ETA on 1.7.7, we are experiencing some really strange client side behavior and would like to upgrade to Socket.IO Client 1.3.3 in the hopes that it will resolve the issue.  If it doesnt we would at least be solid knowing that its still a issue in their code and can then put in a ticket in the Socket.IO Client github.
