### ISSUE TITLE
netty 4.1.15 is broken

### ISSUE THREAD

**Issue by jonfreedman** [mrniko/netty-socketio#480]
The `io.netty.channel.ChannelOutboundBuffer` class in netty 4.1.15 attempts to call `PlatformDependent.newAtomicIntegerFieldUpdater` which does not exist in 4.1.15.  Using netty-transport and netty-common 4.1.16.Final fixes this.

This manifests itself with the following stack trace
```
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
	at com.corundumstudio.socketio.SocketIOServer.startAsync(SocketIOServer.java:151)
	at com.corundumstudio.socketio.SocketIOServer.start(SocketIOServer.java:123)
	at <snip>
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater(Ljava/lang/Class;Ljava/lang/String;)Ljava/util/concurrent/atomic/AtomicIntegerFieldUpdater;
	at io.netty.channel.ChannelOutboundBuffer.<clinit>(ChannelOutboundBuffer.java:92)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.<init>(AbstractChannel.java:421)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.<init>(AbstractNioChannel.java:218)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:58)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.<init>(AbstractNioMessageChannel.java:58)
	at io.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:47)
	at io.netty.channel.nio.AbstractNioMessageChannel.newUnsafe(AbstractNioMessageChannel.java:35)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:80)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:85)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:71)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	... 82 common frames omitted
```

**Comment by 0lig** [comment]
Same here

**Comment by mariokorte** [comment]
We have the same error here. The only solution was to manually force to use 4.1.16.Final of the io.netty dependencies via <dependencyManagement>

Please fix!

**Comment by pablojr** [comment]
@mariokorte you are more than welcome to provide a patch :-)

**Comment by jonfreedman** [comment]
The patch is trivial, just update to a newer version of Netty.  It's probably more important to add a test which actually exercises a socket connection - we have a test case which failed after the upgrade.

**Comment by mrniko** [comment]
Done

**Comment by pgamaster** [comment]
I just imported the latest version of the library and got this error. I believe it's not fixed yet?

Had to manually patch it:

        <dependency>
            <groupId>com.corundumstudio.socketio</groupId>
            <artifactId>netty-socketio</artifactId>
            <version>1.7.13</version>
        </dependency>

        
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport</artifactId>
            <version>4.1.16.Final</version>
        </dependency>

        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>4.1.16.Final</version>
        </dependency>
